---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngcustom-depl
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/scheme: http
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ngcustom
        image: tao0:5000/ngcustom:latest
        ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 500Mi

