apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ngcustom-rs
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/scheme: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngcustom
  template:
    metadata:
      labels:
        app: ngcustom
    spec:
      containers:
      - name: ngcustom
        image: image-registry.openshift-image-registry.svc:5000/homenet/ngcustom
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
